# Destroy all existing records to avoid duplicates
puts 'Cleaning Database 🧼'
Teacher.destroy_all
Student.destroy_all

# Create new teacher records
Teacher.create(name: "Emma Anna Agneta Rünzel", bio: "Hey everyone! I'm Emma, and initially, I studied linguistics and literature, but I have been working in full-stack development within languages and beekeeping (don't ask haha) for some time now. Batch #741 ☀️")
Teacher.create(name: "Lucas Grüner", bio: "Hi, I'm Lucas. I'm from France and my background's in economics. In the past, I've worked both at an investment bank and at a pastry shop. Now embracing my inner geek as a web developer.")
Teacher.create(name: "Iratxe Garrido", bio: "Batch # 1401 I studied Computer Science in Spain and moved to Germany to do a Master in IT-Security. I've worked as a security engineer and penetration tester for the last 7 years, securing systems and breaking into them. Now I'm re-learning how to code so I can also build things and not just break them. I'm a hardcore backend person with a gift to design extremely ugly frontend. I love bouldering 🧗‍♀️, cycling 🚲 and hiking 🏔️, solving Rubik's cubes and spicy food 🌶️")
Teacher.create(name: "Olivier Girardot", bio: "- Teacher @ Le Wagon - Sound Designer & Music Composer - Founder of BamSFX.com")
Teacher.create(name: "Hamza Hanfi", bio: "I am an electrical engineer who look for a career switch, and I think that le wagon is the best choice, regarding the technical level, last year I did start a custom web development self-taught program which allows me to acquire basic knowldge as ( html css JS ) ,")
Teacher.create(name: "Bryan Leighton", bio: "I had studied International Relations at university and decided to work as an EMT for around two years. I plan to try to continue as a web developer and hopefully learn other languages and possibly go into game design!")
Teacher.create(name: "Alexander Dubovoy", bio: "I completed batch #171 in Berlin in the summer of 2018. On the side, I play music professionally, particularly jazz/improvisational piano. I graduated from Yale in 2016 with a degree in History, where I wrote my thesis on the history of jazz in the Soviet Union. From there, I moved to London, where I worked for an international women's rights law firm. Now that I've learned to code, I am a freelance fullstack developer in Berlin and a co-founder at Obst Digital, a design/dev collective with other Le Wagon alums. I love that, as a freelancer, I can continue my music career and continue gigging, touring, etc., while also working as a developer and teaching for Le Wagon. Sometimes, I merge these passions and am working on several computer music projects.")
Teacher.create(name: "Louise Giraud", bio: "Alumini from batch 1401 🫶. Before staring my coding journey, I was working in content and translation as project manager. When I'm not typing lines of codes, you can probably find me listening to music or at a theater rehearsal.")
Teacher.create(name: "Soojin Kim", bio: "The fabulous Speak & Code #1282 Alumni, former marketeer, and currently an enthusiastic web dev learner.")
Teacher.create(name: "Kat Syddall", bio: "Originally from the UK but a Berliner at heart. Recent Le Wagon Web Development graduate, and current student at 42 Berlin. Artist, musician and nature enthusiast 🌿")
Teacher.create(name: "Elisabeth Messmer", bio: "#Batch-1141, Berlin 💪🏼 TA & occasional giver of lectures @ Le Wagon 😬")
Teacher.create(name: "Rodrigo Hoffmann", bio: "I’m a Business Administration professional with 7+ years of experience. I worked in several positions and industries, which helped me to develop a broad vision in organizations. Originally from Chile, I moved to Germany to pursue an MBA and keep growing personally and professionally. Recently graduated from Le Wagon full-stack web development bootcamp, and hired as a TA to support the learning process of new students in the social project 'Speak and Code' program dedicated to successfully inserting foreigners into the German job market, and for the new Data Analytics bootcamp.")
Teacher.create(name: "Stella Raab", bio: "Hey, I'm Stella, a former UI-designer from Berlin. Having worked in product-development and designing websites for the past years, I'm happy to share my knowledge and advice about everything frontend- and design-related. Besides coding I draw and eat things.")
Teacher.create(name: "Joshua Smith", bio: "makes the best lewagon brownies")
Teacher.create(name: "Emre Ebeturk", bio: "Here is a proud Le Wagon Web Development #952 graduate with a philosophy PhD, and a business administration major. After having taught philosophy, ethics, logic and critical thinking for several years at various universities, I decided to move on to a field where I can have a closer connection with today's world. Here I am, enjoying the ever-new challenges of coding and continuously learning from a wonderful community of interesting people. Teaching is my passion, and I live to see the students’ joy in figuring out how to overcome a challenge. Besides coding, find me to talk about philosophy, composing, and life in Berlin.")
Teacher.create(name: "Elaine Pinheiro", bio: "After giving up on being an opera singer, I became a clinical psychologist with experience in mental health, psychotherapy, and psychiatric disorders. My MSc. in Neuroscience led me to computational neuroscience and the amazing world of data. Some of my (many) other interests are music, visual arts, gastronomy, traveling, economics, and social studies. Feel free to get in touch!")

puts "#{Teacher.count} Teachers created successfully! 🌱🌱🌱🌱"

# Create new student records
Student.create(name: "Marco Baaß", bio: "I was working for over 15 years as freelance photographer and retoucher. I like to learn coding for a career change. So after the bootcamp my goal is to work in the field of web development.")
Student.create(name: "Christian Breuckmann", bio: "Learning how to code, from a product design background. Ready for new challenges. Eagerness to solve problems and able to expand my design knowledge with coding.")
Student.create(name: "Julián Federico Burgos", bio: "I have been traveling around the world, living in different countries and working in different kind of jobs. Since I was a teenager I was into coding and making websites in the times of Dreamweaver. I have been wanting to master these skills for a long time and now I am very motivated about it.")
Student.create(name: "Soňa Chaboud", bio: "Coming from non-tech background (theatre), after first year of learning (self and guided) coding I am still a beginner and need to deepen my knowledge, get more experience and confidence during building new projects. My goal is to have the first coding job this year.")
Student.create(name: "Mahdi Fazel", bio: "Senior Product Designer with over 12 years of experience in UX/UI design and software development.")
Student.create(name: "Jonatas Furtado Do Amaral", bio: "I studied linguistics in Brazil and did an MBA in Germany. In recent years I have worked as a project manager in the public and private sector. I want to increase my IT knowledge in order to work with digitalization of processes in the public sector and maybe later become self-employed.")
Student.create(name: "Eduardo Gonzalo Carvalho", bio: "Passionate entrepreneur enthusiast on a mission to innovate and create. Constantly seeking new ventures and opportunities. Let's build something amazing together!")
Student.create(name: "Jeremy Hanhoff", bio: "Former Psychology student who took a turn to marketing and acting, now wants to explore coding to become more flexible and free in my work. I hope that I can achieve a great fundamental set of coding skills and directions to improve myself further.")
Student.create(name: "Alexander Holz", bio: "With a background in law and business, I work as a Data and AI compliance consultant, assisting organizations in navigating the regulatory landscape surrounding the use of emerging technologies. One of my key focuses is the intersection between privacy and AI. I actually signed up for the Data Science Bootcamp. However, I was a bit overwhelmed by the level that is apparently required to follow the course. That's why I want to start with the basics of coding and then move on to the technical side of AI in future iterations. I attend the bootcamp primarily to improve my technical skills and to better understand the technical perspective of my clients.")
Student.create(name: "Franziska Horn", bio: "I am part of a technical operations team and want to improve my technical knowledge with this bootcamp. Looking forward to learning a lot in the upcoming weeks.")
Student.create(name: "Remi Ii", bio: "Hello,everyone! I am currently selling my hand-made goods in the market after 3 years experience of architectural marketing. Through this course, I would like to create and develop my own website and online shop.")
Student.create(name: "Ifechukwu Precious Kanu", bio: "Hi all, My name is Precious, I currently reside in Berlin and this is my first bootcamp. My interest peaked when I watched a friend build a tic-tac-toe game, I was both very impressed and jealous. In short, I wanna use this skill to not only create anew but to build and improve on existing software.")
Student.create(name: "Basria Kouhyar", bio: "Hello, I am Basria Kouhyar. I have a strange interest in Web Development and am eager to learn more about it. The ability to create and shape digital experiences. I am eager to dive into the world of coding.")
Student.create(name: "Clémence Lemaire", bio: "I am Clémence Lemaire. I am French. I have been living in Berlin for 2 and a half years. I have been a designer all of my professional life, starting as a graphic designer and swift to be a full-time UX UI designer about 13 years ago. I am currently unemployed and look forward, through this course, to expand my knowledge in web development in order to master a little bit more my design skills (hand over to the developers and design system building) as well as being able to build by myself a live mockup of a personal project that I have been working on and off on for a couple of years.")
Student.create(name: "Luise von Münchhausen", bio: "Studied biology and art history and worked in several fields with just a few coding experiences. Planning to be either hired or freelancing as a webdeveloper.")
Student.create(name: "Roberto Piazzolla", bio: "Hello! I am Roberto, I am 37 years old and I originally come from Italy. I have always been very passionate about computers since I got my first PC back in 1997, as the World Wide Web started spreading and got in everybody's houses, a truly exciting time. I love videogames and the newest advancements in computer graphics, dancing and ancient history. I started playing during the transition between 2D and 3D graphics. It was rather fascinating to me seeing how much PC hardware could be pushed in order to render amazing virtual worlds. One of my hobbies has always been building my own PCs and/or helping others building one, other than solving any issue that might have occurred. Also, being my partner a DJ, we really like going dancing together. It's a good way to relieve stress and have a good time. Another big passion of mine are ancient civilisations: over many years I have in fact studied Roman and Greek Archaeology. Art, architecture and history are some of my favorite subjects. I have been living in Berlin for 10 years, during this time I have been active in the gastronomy while also learning German and attending to the university. Then finally I had the chance to manage a Cafe in Mitte. After being laid off I have decided to leave this work field for good and start something new and completely different, something that I have always been willing to do, namely working in as a developer. The main reason for this is my curiosity, rather than being a passive actor using apps and websites I want to know how they work from the inside-out, understand the code that's behind it and how you can keep all the systems running efficiently, finally being able to create something on my own with the help of others. In the future I would really love to find a job as a backend developer, but I think this is for me just the beginning, as soon as I acquire more experience and knowledge I am willing to also try other fields in CS, I still have to find out which ones exactly.")
Student.create(name: "Jeremy Rome", bio: "Worked in the Tech industry for the last 7 years, varying roles from Sales to Strategy & Operations. Lived in Berlin for the last 3 years and interested in Startups, tech and sports.")
Student.create(name: "Brian David Sauls", bio: "Hi, my name is Brian and I'm a freelance musician from Berlin. Music isn't the most stable endeavor so I have been looking to change careers. I explored a lot of things and ultimately decided that programming was for me. I'm not sure where my journey is going to lead, but I know that I'm fascinated by both Backend and Frontend-Development, so I'm open for everything.")
Student.create(name: "Alina Shabalina", bio: "I was a QA Automation Engineer before. I want to start my Software Developer Career now. I want to learn JavaScript to work for a company which makes a difference")
Student.create(name: "Bruno Thormählen", bio: ". . .")
Student.create(name: "Tuo Wang", bio: "Product Designer with a background in Game-Animation Design studies and several years of experience in marketing, art and 3D Product Design.")
Student.create(name: "Sachini Weragodavidana", bio: "After working as a lawyer in Sri Lanka for many years, I decided to explore something new. I've always been fascinated by technology, so I've started learning web development.")
Student.create(name: "Alberto Zech", bio: "I am a former Mediadesigner (Camera Operator/Cutter). During the Covid Pandemic I decided to change my profession. I was always fascinated by the art of coding and the opportunities it has to offer. After I finish my web development course I hope to find a company that provides me with interesting projects and smart co-workers to help me improve my coding skills.")

puts "#{Student.count} Students created successfully! 🌱🌱🌱🌱"
